### ISSUE TITLE
`argument_type_not_assignable` on bool when `strict-casts: true`

### ISSUE THREAD

**Issue by SunlightBro** [simc/crimson#22]
If the analysis_options.yaml enforces strict-casts for you project
```yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    # 
    strict-inference: true
    strict-raw-types: true
```

The generated code for assigning a bool will have a `invalid_assignment` error
```dart
        case -6615550055289275125: // hello
          hello = read();
          break;
```
